openapi: 3.0.4
info:
  title: Communication contract between application back-end and bot service
  description: This file defines the communication contract between the AI league application back-end and the different bot services.
  version: 1.0.0

servers:
  - url: http://localhost:8080/{version}
    variables:
      version:
        default: api/v0
        description: API version prefix

paths:

components:
