openapi: 3.0.4
info:
  title: Communication contract between application back-end and bot service
  description: This file defines the communication contract between the AI league application back-end and the different bot services.
  version: 1.0.0

servers:
  - url: http://localhost:8080/{version}
    variables:
      version:
        default: api/v0
        description: API version prefix

paths:
  /api/message:
    post:
      summary: Send a message to the AI model
      description: Sends a message to the AI model adapter and receives a response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The message to send to the AI model adapter.
                context:
                  type: string
                  description: The context for the message, if applicable.
              required:
                - message
      responses:
        '200':
          description: Successful response from the AI model adapter
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The response from the AI model adapter.
